MCResourcePile/mcresourcepile.github.io

assets/materials/lifeboat/map-listing.js

by Brottweiler and Dino_Saurus

Add Dynamo and DynaboOo

---

assets/materials/lifeboat/map-listing.js

Add Winterhold

---

staff/Nanu.html

Adding some info on my profile.

Update profile information.

---

assets/js/gitzip-api.js
mapstack/lifeboat.html

I think this will fix it, but the GitHub API is just returning 404s on my local page, so here goes nothing

Fix including licenses for map downloads

---

src/data/mapstack/overcast.json

My maps should have `CC BY_NC_SA` license.

Dynamo, DynaboOo and Winterhold are non-commercial

---

src/data/mapstack/overcast.json

by JoeltheMole, kp10708
----
Permission was given by [JoelTheMole](https://oc.tc/JoeltheMole) ([reddit](https://www.reddit.com/user/JoelTheMole)) at `2017-01-26T10:46:01+00:00`.

Add Wooly Woods

---

src/data/mapstack/overcast.json

I made a pull request for these to be added to the database, this is for them to be added to the web
Arodisae, Pentamill, Shave Harambe, Cosmic Assault

Add 4 maps

---

src/assets/css/index.css
src/assets/css/main.css
src/partials/footer.html

http://puu.sh/tNqRl/4aa398cdf4.png
- Looks better
- Much better for mobile devices (current one it really broken on small screens)

Update global footer

---

src/index.html

It annoyed me.
Btw we should talk some day or something 🙂

Fix Mitch's terrible splash capitalisation 👮🏻

---

src/admin/preferences.html
src/assets/js/preferences.js

Also fixes a bug where you could put a bunch of spaces into the token field and save that.

Preferences refactor

---

src/assets/css/main.css
src/assets/js/maps-commons.js
src/partials/map-thumbnail.html
src/partials/map.html

Improves the visual quality of map download modals.

Downloads visual revamp

---

src/data/maps/stratus.json

Mini Map Making Competition url changed from min_map_competition to mini_map_making_competition in a prior update

Update links to Mini Map Making Competion maps

---

src/admin/preferences.html
src/assets/css/main.css
src/assets/js/maps-commons.js
src/assets/js/preferences.js
src/partials/page_maps.html

Show a small collection of related maps to the one just downloaded as a suggestion to what the user may also like. Suggestions are based on the map's authors and tags, which are compared to the rest of the selected collection.

Suggested maps

---

src/data/leagues/stratus/index.json
src/data/leagues/stratus/stranger_cores.json
src/leagues/stratus/stranger_cores.html

**Check Thoroughly**  
I've not done the TM format before so who knows

Add Stranger Cores to Stratus tournaments

---

src/data/stats/stratus/bow.json

I'm pretty sure I made no mistakes, sorry if I did nixter. Some maps don't show up on OCN resourcepile so I don't know if those will still work... Deadman's Isle, Ruediger's Spooky Garden and Deserted Sanctuary

Some new records

---

src/data/stats/stratus/bow.json

I believe I did everything right, I'll continue to let records build up so it's not so spammy.

More Changes

---

src/data/stats/stratus/bow.json

I know these are really spammy and annoying, so I apologize, to make it even for being so annoying. In my next batch of records I'll put in all of the records from the forum thread so you guys don't have to.

Another Update

---

src/data/stats/stratus/bow.json

Fixed Bluedu's UUID

---

src/data/stats/stratus/bow.json

Added a few of my own but mainly the communities, trying to add some new faces into this medley of shots :D

New Bow Record Update

---

src/data/stats/stratus/bow.json

Added a bunch of people's bow records, still no out of the world because I'm hoping you guys will make a new bow records for that and then I'll also work on that page too. Please consider it <3.

New Bow Records

---

src/data/maps/pgm.json

Remove maps that were added more than 30 days ago

Update new maps section

---

src/data/maps/overcast.json

My proudest work and only in repo map that I actually authored.
Added in pull request MCResourcePile/overcast-maps-o-to-z#1

Add Thin Ice

---

src/data/maps/pgm.json

Adds new maps from the pgm-maps repo and OCC's scrimmage maps repo

Add new PGM maps from MCRP and OCC

---

src/data/maps/pgm.json

remove duplicate ahhhhhh sorry

Add the Community Dropper map

---

.github/workflows/uuids.yml

Rechecks all UUIDs and refreshes usernames if changed

Update UUIDs every month

---

src/data/staff.json
src/staff.html

Hopefully this doesn't break everything

Add past contributors to the staff page

---

src/data/maps/pgm.json

Included are Warzone originals, plus maps from other communities that we've converted to work with the latest version of PGM. Surprisingly, there are a lot of Avicus maps here.
+ fix the wrong tag on the last PR

Add public Warzone maps

---

src/data/contests/overcast/index.json
src/data/contests/stratus/index.json
src/data/tournaments/avicus/index.json
src/data/tournaments/overcast/index.json
src/data/tournaments/pgm/index.json
src/data/tournaments/stratus/index.json
src/data/updates.json
src/partials/pages/components/tm_banner.html
src/updates.html

Changes some properties to resolve conflicts with https://github.com/helpers/handlebars-helpers#date

Fix invalid dates

---

src/assets/js/maps-redux.js
src/partials/pages/maps_redux/components/maps_redux_modal_download.html

Adds quick links between different map variants in the download panel.

Link variants to their respective downloads panel

---

src/partials/pages/maps_redux/components/maps_redux_thumbnail.html

Display which OCC pools each map is currently playing in

---

src/helpers/isNewMap.js
src/partials/pages/maps_redux/components/maps_redux_thumbnail.html

Tag and highlight maps created in the past 2 months

---

.github/workflows/fetch-pgm-maps.yml
.github/workflows/fetch-uuids.yml

For https://github.com/MCResourcePile/map-fetcher/pull/5

Add map sources to pgm.json data file

---

src/data/contests/stratus/index.json

super small fix for the winner of that contest in stratus' page, midgard was there twice

Fix Mini Map Making Competition winner

---

src/data/staff.json

We can add to this/update it as people are eligible for username changes. There's also a couple people on the staff page no longer in our discord.

Update Discord usernames on staff page
